name: Feature request
description: Suggest an idea for this project.
title: "[FEATURE]"

body:
  - type: input
    id: version
    attributes:
      label: Release version
      description: Name and version of the release package used
      placeholder: e.g. AzMigExport v2.0.02252.59
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: Please describe the feature.
      description: What feature would you like to get added? What problem is it solving?
      placeholder: Feature description
    validations:
      required: true