using System.Collections.Generic;

namespace Azure.Migrate.Export.Common
{
    public class CoreReportConstants
    {
        public const string CoreReportDirectory = @".\Core-Report";
        public const string CoreReportName = @"AzureMigrate_Assessment_Core_Report.xlsx";
        public const string BackSlash = @"\";
        public const string CoreReportPath = CoreReportDirectory + BackSlash + CoreReportName;

        public const string PropertiesTabName = "Properties";
        public static readonly List<string> PropertyList = new List<string>
        {
            "Tenant ID",
            "Subscription",
            "Resource Group Name",
            "Azure Migrate Project Name",
            "Assessment Site Name",
            "Workflow",
            "Target Region",
            "Currency",
            "Assessment Duration",
            "Optimization Preference",
            "Assess SQL Services"
        };

        public const string All_VM_IaaS_Server_Rehost_Perf_TabName = "All_VM_IaaS_Server_Rehost_Perf";
        public static readonly List<string> All_VM_IaaS_Server_Rehost_Perf_Columns = new List<string>
        {
            "Machine Name",
            "Environment",
            "Azure VM Readiness",
            "Azure VM Readiness - Warnings",
            "Recommended VM Size",
            "Monthly Compute Cost Estimate (Pay as you go)",
            "Monthly Storage Cost Estimate",
            "Operating System",
            "VM Host",
            "Boot Type",
            "Cores",
            "Memory (in MB)",
            "CPU Utilization (in %)",
            "Memory Utilization (in %)",
            "Storage (in GB)",
            "Network Adapters",
            "IP Addresses",
            "MAC Addresses",
            "Disk Names",
            "Azure Disk Readiness",
            "Recommended Disk SKUs",
            "Standard HDD Disks",
            "Standard SSD Disks",
            "Premium Disks",
            "Ultra Disks",
            "Monthly Storage Cost for Standard HDD Disks",
            "Monthly Storage Cost for Standard SSD Disks",
            "Monthly Storage Cost for Premium Disks",
            "Monthly Storage Cost for Ultra Disks",
            "Monthly Azure Site Recovery Cost Estimate",
            "Monthly Azure Backup Cost Estimate",
            "Group Name",
            "Machine ID"
        };

        public const string SQL_All_Instances_TabName = "SQL_All_Instances";
        public static readonly List<string> SQL_All_Instances_Columns = new List<string>
        {
            "Machine Name",
            "SQL Instance",
            "Environment",
            "Azure SQL MI Readiness",
            "Azure SQL MI Readiness - Warnings",
            "Recommended Deployment Type",
            "Azure SQL MI Configuration",
            "Monthly Compute Cost Estimate (Pay as you go)",
            "Monthly Compute Cost Estimate (Pay as you go + RI)",
            "Monthly Compute Cost Estimate (Pay as you go + AHUB)",
            "Monthly Compute Cost Estimate (Pay as you go + AHUB + RI)",
            "Monthly Storage Cost Estimate",
            "User Databases",
            "SQL Edition",
            "SQL Version",
            "Total DB Size (in MB)",
            "Largest DB Size (in MB)",
            "vCores Allocated",
            "CPU Utilization (in %)",
            "Memory Utilization (in MB)",
            "Number of Disks",
            "Disk Read (in OPS)",
            "Disk Write (in OPS)",
            "Disk Read (in MBPS)",
            "Disk Write (in MBPS)",
            "Azure SQL MI Conifugration - Target Service Tier",
            "Azure SQL MI Conifugration - Target Compute Tier",
            "Azure SQL MI Conifugration - Target Hardware Type",
            "Azure SQL MI Conifugration - Target vCores",
            "Azure SQL MI Conifugration - Target Storage (in GB)",
            "Group Name",
            "Machine ID",
        };

        public const string SQL_IaaS_Instance_Rehost_Perf_TabName = "SQL_IaaS_Instance_Rehost_Perf";
        public static readonly List<string> SQL_IaaS_Instance_Rehost_Perf_Columns = new List<string>
        {
            "Machine Name",
            "SQL Instance",
            "Environment",
            "SQL Server on Azure VM Readiness",
            "SQL Server on Azure VM Readiness - Warnings",
            "SQL Server on Azure VM Configuration",
            "Monthly Compute Cost Estimate (Pay as you go)",
            "Monthly Compute Cost Estimate (Pay as you go + RI)",
            "Monthly Compute Cost Estimate (Pay as you go + AHUB)",
            "Monthly Compute Cost Estimate (Pay as you go + AHUB + RI)",
            "Monthly Compute Cost Estimate (Pay as you go + ASP)",
            "Monthly Storage Cost Estimate",
            "SQL Server on Azure VM - Managed Disk Configuration",
            "User Databases",
            "Recommended Deployment Type",
            "Standard HDD Disks",
            "Standard SSD Disks",
            "Premium Disks",
            "Ultra Disks",
            "Monthly Storage Cost for Standard HDD Disks",
            "Monthly Storage Cost for Standard SSD Disks",
            "Monthly Storage Cost for Premium Disks",
            "Monthly Storage Cost for Ultra Disks",
            "SQL Edition",
            "SQL Version",
            "Total DB Size (in MB)",
            "Largest DB Size (in MB)",
            "vCores Allocated",
            "CPU Utilization (in %)",
            "Memory Utilization (in MB)",
            "Number Of Disks",
            "Disk Read (in OPS)",
            "Disk Write (in OPS)",
            "Disk Read (in MBPS)",
            "Disk Write (in MBPS)",
            "Confidence Rating (in %)",
            "SQL Server on Azure VM Configuration - Target vCores",
            "Monthly Azure Site Recovery Cost Estimate",
            "Monthly Azure Backup Cost Estimate",
            "Group Name",
            "Machine ID"
        };

        public const string SQL_IaaS_Server_Rehost_AsOnPrem_TabName = "SQL_IaaS_Server_Rehost_As-is";
        public static readonly List<string> SQL_IaaS_Server_Rehost_AsOnPrem_Columns = new List<string>
        {
            "Machine Name",
            "Environment",
            "Azure VM Readiness",
            "Recommended VM Size",
            "Monthly Compute Cost Estimate",
            "Monthly Storage Cost Estimate",
            "Operating System",
            "VM Host",
            "Boot Type",
            "Cores",
            "Memory (in MB)",
            "Storage (in GB)",
            "Network Adapters",
            "IP Addresses",
            "MAC Addresses",
            "Disk Names",
            "Azure Disk Readiness",
            "Recommended Disk SKUs",
            "Standard HDD Disks",
            "Standard SSD Disks",
            "Premium Disks",
            "Ultra Disks",
            "Monthly Storage Cost for Standard HDD Disks",
            "Monthly Storage Cost for Standard SSD Disks",
            "Monthly Storage Cost for Premium Disks",
            "Monthly Storage Cost for Ultra Disks",
            "Group Name",
            "Machine ID"
        };

        public const string SQL_IaaS_Server_Rehost_Perf_TabName = "SQL_IaaS_Server_Rehost_Perf";
        public static readonly List<string> SQL_IaaS_Server_Rehost_Perf_Columns = new List<string>
        {
            "Machine Name",
            "Environment",
            "Azure VM Readiness",
            "Azure VM Readiness - Warnings",
            "Recommended VM Size",
            "Monthly Compute Cost Estimate (Pay as you go)",
            "Monthly Compute Cost Estimate (Pay as you go + RI)",
            "Monthly Compute Cost Estimate (Pay as you go + AHUB)",
            "Monthly Compute Cost Estimate (Pay as you go + AHUB + RI)",
            "Monthly Compute Cost Estimate (Pay as you go + ASP)",
            "Monthly Storage Cost Estimate",
            "Operating System",
            "VM Host",
            "Boot Type",
            "Cores",
            "Memory (in MB)",
            "CPU Utilization (in %)",
            "Memory Utilization (in %)",
            "Storage (in GB)",
            "Network Adapters",
            "IP Addresses",
            "MAC Addresses",
            "Disk Names",
            "Azure Disk Readiness",
            "Recommended Disk SKUs",
            "Standard HDD Disks",
            "Standard SSD Disks",
            "Premium Disks",
            "Ultra Disks",
            "Monthly Storage Cost for Standard HDD Disks",
            "Monthly Storage Cost for Standard SSD Disks",
            "Monthly Storage Cost for Premium Disks",
            "Monthly Storage Cost for Ultra Disks",
            "Monthly Azure Site Recovery Cost Estimate",
            "Monthly Azure Backup Cost Estimate",
            "Group Name",
            "Machine ID"
        };

        public const string SQL_MI_PaaS_TabName = "SQL_MI_PaaS";
        public static readonly List<string> SQL_MI_PaaS_Columns = new List<string>
        {
            "Machine Name",
            "SQL Instance",
            "Environment",
            "Azure SQL MI Readiness",
            "Azure SQL MI Readiness - Warnings",
            "Recommended Deployment Type",
            "Azure SQL MI Configuration",
            "Monthly Compute Cost Estimate (Pay as you go)",
            "Monthly Compute Cost Estimate (Pay as you go + RI)",
            "Monthly Compute Cost Estimate (Pay as you go + AHUB)",
            "Monthly Compute Cost Estimate (Pay as you go + AHUB + RI)",
            "Monthly Storage Cost Estimate",
            "User Databases",
            "SQL Edition",
            "SQL Version",
            "Total DB Size (in MB)",
            "Largest DB Size (in MB)",
            "vCores Allocated",
            "CPU Utilization (in %)",
            "Memory Utilization (in MB)",
            "Number of Disks",
            "Disk Read (in OPS)",
            "Disk Write (in OPS)",
            "Disk Read (in MBPS)",
            "Disk Write (in MBPS)",
            "Azure SQL MI Conifugration - Target Service Tier",
            "Azure SQL MI Conifugration - Target Compute Tier",
            "Azure SQL MI Conifugration - Target Hardware Type",
            "Azure SQL MI Conifugration - Target vCores",
            "Azure SQL MI Conifugration - Target Storage (in GB)",
            "Group Name",
            "Machine ID"
        };

        public const string VM_IaaS_Server_Rehost_AsOnPrem_TabName = "VM_IaaS_Server_Rehost_As-is";
        public static readonly List<string> VM_IaaS_Server_Rehost_AsOnPrem_Columns = new List<string>
        {
            "Machine Name",
            "Environment",
            "Azure VM Readiness",
            "Recommended VM Size",
            "Monthly Compute Cost Estimate",
            "Monthly Storage Cost Estimate",
            "Operating System",
            "VM Host",
            "Boot Type",
            "Cores",
            "Memory (in MB)",
            "Storage (in GB)",
            "Network Adapters",
            "IP Addresses",
            "MAC Addresses",
            "Disk Names",
            "Azure Disk Readiness",
            "Recommended Disk SKUs",
            "Standard HDD Disks",
            "Standard SSD Disks",
            "Premium Disks",
            "Ultra Disks",
            "Monthly Storage Cost for Standard HDD Disks",
            "Monthly Storage Cost for Standard SSD Disks",
            "Monthly Storage Cost for Premium Disks",
            "Monthly Storage Cost for Ultra Disks",
            "Group Name",
            "Machine ID"
        };

        public const string VM_IaaS_Server_Rehost_Perf_TabName = "VM_IaaS_Server_Rehost_Perf";
        public static readonly List<string> VM_IaaS_Server_Rehost_Perf_Columns = new List<string>
        {
            "Machine Name",
            "Environment",
            "Azure VM Readiness",
            "Azure VM Readiness - Warnings",
            "Recommended VM Size",
            "Monthly Compute Cost Estimate (Pay as you go)",
            "Monthly Compute Cost Estimate (Pay as you go + RI)",
            "Monthly Compute Cost Estimate (Pay as you go + AHUB)",
            "Monthly Compute Cost Estimate (Pay as you go + AHUB + RI)",
            "Monthly Compute Cost Estimate (Pay as you go + ASP)",
            "Monthly Storage Cost Estimate",
            "Operating System",
            "VM Host",
            "Boot Type",
            "Cores",
            "Memory (in MB)",
            "CPU Utilization (in %)",
            "Memory Utilization (in %)",
            "Storage (in GB)",
            "Network Adapters",
            "IP Addresses",
            "MAC Addresses",
            "Disk Names",
            "Azure Disk Readiness",
            "Recommended Disk SKUs",
            "Standard HDD Disks",
            "Standard SSD Disks",
            "Premium Disks",
            "Ultra Disks",
            "Monthly Storage Cost for Standard HDD Disks",
            "Monthly Storage Cost for Standard SSD Disks",
            "Monthly Storage Cost for Premium Disks",
            "Monthly Storage Cost for Ultra Disks",
            "Monthly Azure Site Recovery Cost Estimate",
            "Monthly Azure Backup Cost Estimate",
            "Group Name",
            "Machine ID"
        };

        public const string VM_SS_IaaS_Server_Rehost_AsOnPrem_TabName = "VM_SS_IaaS_Server_Rehost_As-is";
        public static readonly List<string> VM_SS_IaaS_Server_Rehost_AsOnPrem_Columns = new List<string>
        {
            "Machine Name",
            "Environment",
            "Azure VM Readiness",
            "Recommended VM Size",
            "Monthly Compute Cost Estimate",
            "Monthly Storage Cost Estimate",
            "Operating System",
            "VM Host",
            "Boot Type",
            "Cores",
            "Memory (in MB)",
            "Storage (in GB)",
            "Network Adapters",
            "IP Addresses",
            "MAC Addresses",
            "Disk Names",
            "Azure Disk Readiness",
            "Recommended Disk SKUs",
            "Standard HDD Disks",
            "Standard SSD Disks",
            "Premium Disks",
            "Ultra Disks",
            "Monthly Storage Cost for Standard HDD Disks",
            "Monthly Storage Cost for Standard SSD Disks",
            "Monthly Storage Cost for Premium Disks",
            "Monthly Storage Cost for Ultra Disks",
            "Group Name",
            "Machine ID"
        };

        public const string VM_SS_IaaS_Server_Rehost_Perf_TabName = "VM_SS_IaaS_Server_Rehost_Perf";
        public static readonly List<string> VM_SS_IaaS_Server_Rehost_Perf_Columns = new List<string>
        {
            "Machine Name",
            "Environment",
            "Azure VM Readiness",
            "Azure VM Readiness - Warnings",
            "Recommended VM Size",
            "Monthly Compute Cost Estimate (Pay as you go)",
            "Monthly Compute Cost Estimate (Pay as you go + RI)",
            "Monthly Compute Cost Estimate (Pay as you go + AHUB)",
            "Monthly Compute Cost Estimate (Pay as you go + AHUB + RI)",
            "Monthly Compute Cost Estimate (Pay as you go + ASP)",
            "Monthly Storage Cost Estimate",
            "Operating System",
            "VM Host",
            "Boot Type",
            "Cores",
            "Memory (in MB)",
            "CPU Utilization (in %)",
            "Memory Utilization (in %)",
            "Storage (in GB)",
            "Network Adapters",
            "IP Addresses",
            "MAC Addresses",
            "Disk Names",
            "Azure Disk Readiness",
            "Recommended Disk SKUs",
            "Standard HDD Disks",
            "Standard SSD Disks",
            "Premium Disks",
            "Ultra Disks",
            "Monthly Storage Cost for Standard HDD Disks",
            "Monthly Storage Cost for Standard SSD Disks",
            "Monthly Storage Cost for Premium Disks",
            "Monthly Storage Cost for Ultra Disks",
            "Monthly Azure Site Recovery Cost Estimate",
            "Monthly Azure Backup Cost Estimate",
            "Group Name",
            "Machine ID"
        };

        public const string WebApp_IaaS_Server_Rehost_AsOnPrem_TabName = "WebApp_IaaS_Server_Rehost_As-is";
        public static readonly List<string> WebApp_IaaS_Server_Rehost_AsOnPrem_Columns = new List<string>
        {
            "Machine Name",
            "Environment",
            "Azure VM Readiness",
            "Recommended VM Size",
            "Monthly Compute Cost Estimate",
            "Monthly Storage Cost Estimate",
            "Operating System",
            "VM Host",
            "Boot Type",
            "Cores",
            "Memory (in MB)",
            "Storage (in GB)",
            "Network Adapters",
            "IP Addresses",
            "MAC Addresses",
            "Disk Names",
            "Azure Disk Readiness",
            "Recommended Disk SKUs",
            "Standard HDD Disks",
            "Standard SSD Disks",
            "Premium Disks",
            "Ultra Disks",
            "Monthly Storage Cost for Standard HDD Disks",
            "Monthly Storage Cost for Standard SSD Disks",
            "Monthly Storage Cost for Premium Disks",
            "Monthly Storage Cost for Ultra Disks",
            "Group Name",
            "Machine ID"
        };

        public const string WebApp_IaaS_Server_Rehost_Perf_TabName = "WebApp_IaaS_Server_Rehost_Perf";
        public static readonly List<string> WebApp_IaaS_Server_Rehost_Perf_Columns = new List<string>
        {
            "Machine Name",
            "Environment",
            "Azure VM Readiness",
            "Azure VM Readiness - Warnings",
            "Recommended VM Size",
            "Monthly Compute Cost Estimate (Pay as you go)",
            "Monthly Compute Cost Estimate (Pay as you go + RI)",
            "Monthly Compute Cost Estimate (Pay as you go + AHUB)",
            "Monthly Compute Cost Estimate (Pay as you go + AHUB + RI)",
            "Monthly Compute Cost Estimate (Pay as you go + ASP)",
            "Monthly Storage Cost Estimate",
            "Operating System",
            "VM Host",
            "Boot Type",
            "Cores",
            "Memory (in MB)",
            "CPU Utilization (in %)",
            "Memory Utilization (in %)",
            "Storage (in GB)",
            "Network Adapters",
            "IP Addresses",
            "MAC Addresses",
            "Disk Names",
            "Azure Disk Readiness",
            "Recommended Disk SKUs",
            "Standard HDD Disks",
            "Standard SSD Disks",
            "Premium Disks",
            "Ultra Disks",
            "Monthly Storage Cost for Standard HDD Disks",
            "Monthly Storage Cost for Standard SSD Disks",
            "Monthly Storage Cost for Premium Disks",
            "Monthly Storage Cost for Ultra Disks",
            "Monthly Azure Site Recovery Cost Estimate",
            "Monthly Azure Backup Cost Estimate",
            "Group Name",
            "Machine ID"
        };

        public const string WebApp_PaaS_TabName = "WebApp_PaaS";
        public static readonly List<string> WebApp_PaaS_Columns = new List<string>
        {
            "Machine Name",
            "Web Application Name",
            "Environment",
            "Azure App Service Readiness",
            "Azure App Service Readiness - Warnings",
            "App Service Plan",
            "Recommended SKU",
            "Monthly Compute Cost Estimate (Pay as you go)",
            "Monthly Compute Cost Estimate (Pay as you go + RI)",
            "Monthly Compute Cost Estimate (Pay as you go + ASP)",
            "Azure Recommended Target",
            "Group Name",
            "Machine ID"
        };
    }
}